name: RageMode
main: at.dafnik.ragemode.Main.Main
author: Dafnik
version: 1.4.0
commands:
  rm:
    description: RageMode Admin Commands!
    aliases: ragemode
  vote:
    description: Vote for a Map
    aliases: v
  list:
    description: List all Maps
  tpmap:
    description: Teleport to a Map
  tplobby:
    description: Teleport to Lobby
  forcestart:
    description: Forcestart the round
    aliases: start
  latestart:
    description: Reset the Counter
  stats:
    description: Show you, your stats
  statsadmin:
    description: Edit all stats
  hub:
    description: Back to the hub
    aliases: [l, leave, return, h]
  statsreset:
    description: Reset your Stats
  coins:
    description: Show you your Coins
    aliases: c
  coinsadmin:
    description: Admin Command
  test:
    description: Test