name: RageMode
main: at.dafnik.ragemode.Main.Main
author: Dafnik
version: 1.4.1
commands:
  rm:
    description: List of all RageMode commands
    aliases: ragemode
  vote:
    description: Vote for a Map
    aliases: v
  list:
    description: During lobby periode: Display all voteable maps. During Game: Display current map
  tpmap:
    description: Teleport to map
  tplobby:
    description: Teleport to lobby
  forcestart:
    description: Starts the game earlier
    aliases: start
  latestart:
    description: Reset the Counter
  stats:
    description: Display your stats
  statsadmin:
    description: Admin Command. Edit stats from users
  hub:
    description: Leave the current game and join the lobbyserver
    aliases: [l, leave, return, h]
  statsreset:
    description: Reset your stats
  coins:
    description: Show you your coins
    aliases: c
  coinsadmin:
    description: Admin Command. Add or remove coins from users
  sparcles:
    description: Enable or disable sparcles behind your arrows
    aliases: sparcle
  test:
    description: Test (Nothing special)